### ISSUE TITLE
安装weditor库报错

### ISSUE THREAD

**Issue by lilacly** [Chras-fu/Liuma-engine#14]

**Comment by lilacly** [comment]
Collecting weditor
  Using cached weditor-0.7.3.tar.gz (2.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Error parsing
      Traceback (most recent call last):
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\core.py", line 105, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
                                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\packaging.py", line 854, in get_version
          version = _get_version_from_pkg_metadata(package_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-q61qg78l\normal\Lib\site-packages\pbr\packaging.py", line 822, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Programs\Python\Python311\Lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
                 ^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 795: illegal multibyte sequence
      error in setup command: Error parsing C:\Users\29921\AppData\Local\Temp\pip-install-10_o2j0o\weditor_eb2a32d43b6c4b28a46d181fcf930c38\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 795: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\29921>pip cache purge
Files removed: 118

C:\Users\29921>pip install weditor
Collecting weditor
  Downloading weditor-0.7.3.tar.gz (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Error parsing
      Traceback (most recent call last):
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\core.py", line 105, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\util.py", line 272, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\hooks\base.py", line 27, in run
          self.hook()
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\hooks\metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
                                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\packaging.py", line 854, in get_version
          version = _get_version_from_pkg_metadata(package_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Temp\pip-build-env-b05d2k6c\normal\Lib\site-packages\pbr\packaging.py", line 822, in _get_version_from_pkg_metadata
          pkg_metadata = email.message_from_file(pkg_metadata_file)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Programs\Python\Python311\Lib\email\__init__.py", line 54, in message_from_file
          return Parser(*args, **kws).parse(fp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\29921\AppData\Local\Programs\Python\Python311\Lib\email\parser.py", line 53, in parse
          data = fp.read(8192)
                 ^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 795: illegal multibyte sequence
      error in setup command: Error parsing C:\Users\29921\AppData\Local\Temp\pip-install-eab9apxi\weditor_f0784fc7a58e48b7bbddad49a13cc88b\setup.cfg: UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 795: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hfning** [comment]
我也碰见此类问题，我是升级了python版本后就无法安装weditor了，不知道你有没有解决此问题？
